### ISSUE TITLE
There is no Tun2SocksKit module with the binary release file

### ISSUE THREAD

**Issue by raitech12** [arror/Tun2SocksKit#6]
Hi,
I import the binary file into my xcode project but the only library is ```HevSocks5Tunnel``` there is no ```Tun2SocksKit``` package.

what is wrong with it?

Thanks

**Comment by alexjane19** [comment]
Are you sure? because I import it it works well. how did you import it to your xcode?

**Comment by arror** [comment]
> 

没有使用 SPM 导入 Tun2SocksKit 依赖。
