### ISSUE TITLE
it possible to use tun2sockskit in macos developer id exporting 

### ISSUE THREAD

**Issue by hosseinkhojany** [arror/Tun2SocksKit#9]

**Comment by netyouli** [comment]
这个Tun2SocksKit怎么使用，有demo吗
<img width="981" alt="image" src="https://github.com/arror/Tun2SocksKit/assets/5723961/77ddd1aa-dad8-4b84-84b4-9b5ae207257e">
我这边集成了一下，运行会进fatalError导致闪退

**Comment by vanyasem** [comment]
@netyouli have you managed to solve it?
